int32 IGNORE_PARAMETER = -1 

bool right_wall
bool left_wall
bool front_wall
bool back_wall
int32 timeout

---------
int8 SUCCESS = 0
int8 TIME_OUT = 1
int8 NUM_DATA_MISSMATCH = 2
int8 PREEMTING = 99

int8 result
string text
uint8 sequence

int64 total_time

---------

int8 sequence 
string text
int64 timeout

int64 total_time
